### ISSUE TITLE
疑问

### ISSUE THREAD

**Issue by cjcj125125** [LX1309244704/SpringBoot-master#2]
https://github.com/LX1309244704/SpringBoot-master/blob/eb342bc33fb0f8b6a86fa27fb9e3cffc1070baae/springboot-redis/springboot-redis-service/src/main/java/com/redis/config/RedisConfig.java#L43

看了您的demo受益匪浅，请教这一句有什么作用？？？

**Comment by LX1309244704** [comment]
由于参数可能不同, hashCode肯定不一样, 缓存的key也需要不一样

**Comment by LX1309244704** [comment]
由于参数可能不同,  缓存的key也需要不一样
