### ISSUE TITLE
添加quartz时出现外键关联问题导致不能添加成功

### ISSUE THREAD

**Issue by yuanzhijin** [LX1309244704/SpringBoot-master#4]

**Comment by LX1309244704** [comment]
能否把具体错误发出来

**Comment by yuanzhijin** [comment]
抱歉了，是我本地数据库配置只识别大写，然后全局替换sql脚本大写时前面多了个空格，导致外键出现问题才出现添加不成功问题，目前问题已经解决了，也已经能正常使用定时任务了，敬请谅解冒昧提出的issue在此非常感谢您的回复！
    
        祝：工作顺利


15754715473@163.com
 
发件人： LX1309244704
发送时间： 2019-01-14 08:43
收件人： LX1309244704/SpringBoot-master
抄送： 袁之晋; Author
主题： Re: [LX1309244704/SpringBoot-master] 添加quartz时出现外键关联问题导致不能添加成功 (#4)
能否把具体错误发出来
